### ISSUE TITLE
Missing script: "ngx-sitemap"

### ISSUE THREAD

**Issue by ahmedbilal205** [remy-marthaler/ngx-sitemap#1]
How do I use it to generate the sitemap? After installing it, it doesn't generate any script. Running the command "ngx-sitemap <srcDirectory> <baseUrl>" give the following error (The term 'ngx-sitemap' is not recognized as the name of a cmdlet) and trying to run it using npm run gives the error (Missing script: "ngx-sitemap"). Any proper documentation / guide would help

**Comment by remy-marthaler** [comment]
Running `ngx-sitemap` after installing should work. Did you run the command within your project? Also, did you checkout the documentation in the readme? I think the problem is npm not recognizing the package and has nothing to do with my package not working (just tested it again locally and it also runs every night on my server). If you could further explain what you did, maybe I can help you better.

**Comment by ahmedbilal205** [comment]
Thanks for replying, the issue was indeed npm not recognizing the package. Running it with npx as (npx ngx-sitemap "srcDirectory" "baseUrl" ) fixed the issue.
